### ISSUE TITLE
implement ping

### ISSUE THREAD

**Issue by tsloughter** [erleans/pgo#12]
Currently the ping to check on connections is not being done and simply acts as a success. Implement a ping to the postgres server to verify the connection is working and reconnect if it is not.

**Comment by benbro** [comment]
Isn't it implemented here?
https://github.com/erleans/pgo/blob/master/src/pgo_handler.erl#L81

**Comment by tsloughter** [comment]
Hm, I guess so :) https://github.com/erleans/pgo/commit/8daa4f97e36efe62a1bc77439250be0f996ecb2c

Weird that i would implement it 2 days later but forget to close this. Hopefully I'm not forgetting anything :)

Thanks!

**Comment by benbro** [comment]
Do you check somewhere for response or will the socket automatically detect the problem?

**Comment by tsloughter** [comment]
The connection process crashes if it doesn't return `ok`.

**Comment by benbro** [comment]
Thanks
