### ISSUE TITLE
float_datetimes and datetime_float_seconds not documented in README

### ISSUE THREAD

**Issue by benbro** [erleans/pgo#14]
Is it because the options not public or stable?
[float_datetimes](https://github.com/erleans/pgo/blob/c4cb0c2e70958e32b2332934d94a06ccc46f1680/src/pgo_protocol.erl#L1042)
[datetime_float_seconds](https://github.com/erleans/pgo/blob/c4cb0c2e70958e32b2332934d94a06ccc46f1680/src/pgo_protocol.erl#L989)

**Comment by tsloughter** [comment]
Aren't those set by the server? I still need to fix it (currently hardcoded to integer) but my understanding was that these are parameters queried for from the server to set how the client will handle them.

**Comment by benbro** [comment]
I thought they are part of decode_opts => [decode_option()]} in the README.
I'm not familiar with the code. I can close the issue if this is not relevant.

**Comment by tsloughter** [comment]
Yea, I don't think it is.

And in current master pgo I removed float datetimes and it is just integer.
