### ISSUE TITLE
Warning message from telemetry

### ISSUE THREAD

**Issue by yogesch** [erleans/pgo#19]
Accessing the database for just about anything using pgo gives a warning - 
`Using execute/3 with a single event value is deprecated. Use a measurement map instead.`

On checking around a bit, this error message seems to be from telemetry. Some other apps seem to have had the same issue, e.g. https://github.com/nats-io/nats.ex/issues/85 
But I am uncertain if their solution strategy of simply hiding telemetry warning is the right one..

**Comment by tsloughter** [comment]
Ah ok, I'll get that fixed, just need to update the use of `execute`.

**Comment by tsloughter** [comment]
It should be fixed now in master and hex package 0.8.0.

**Comment by yogesch** [comment]
Just checked it again, it works! Thank you 👍
