### ISSUE TITLE
Error encoding infinity

### ISSUE THREAD

**Issue by benbro** [erleans/pgo#37]
```erlang
pgo:query(<<"SELECT tstzrange($1, $2, '[)');">>, [{{2020,1,1},{0,0,0}}, infinity]).
{error,function_clause}
```

**Comment by tsloughter** [comment]
Ah, yup, looks like we only support decoding time to infinity, not encoding. Should be an easy enough fix in pg_types that I'll get to today.

**Comment by tsloughter** [comment]
@benbro fix pushed to master. Can you give it a try.

**Comment by benbro** [comment]
Works in master. Thanks.
