### ISSUE TITLE
Set pgo:query/3 timeout

### ISSUE THREAD

**Issue by benbro** [erleans/pgo#50]
Is there a way to set a timeout for pgo:query/3? I couldn't find a way to increase it.
I have SQL query that deleted many records and takes a long time.

**Comment by tsloughter** [comment]
Yea, but looks like it is confusing to do and I should improve it (plus add a test for it!). Pretty sure it is a timeout under the `pool_options`, so something like:

```
pgo:query(Query, Params, #{pool_options => [{timeout, 60000}]})
```

**Comment by benbro** [comment]
Isn't this timeout for getting a worker from the pool and not for executing the query?
Also, does it make sense to have an option to send a query without waiting for a response?

**Comment by tsloughter** [comment]
Na, pretty sure the timeout there is for how long you can hold on to the connection.

**Comment by benbro** [comment]
I'll try it. thanks.
