### ISSUE TITLE
Support for SCRAM Authentication

### ISSUE THREAD

**Issue by jkatz** [erleans/pgo#52]
Support for [SCRAM password authentication](https://www.postgresql.org/docs/current/sasl-authentication.html) was introduced in PostgreSQL 10; PostgreSQL 14 defaults to using [`scram-sha-256`](https://www.postgresql.org/docs/14/release-14.html) for password hashing by default:

> Change the default of the password_encryption server parameter to scram-sha-256 

While the `md5` is still supported, it is gradually being phased out in favor of SCRAM.

If you need some reference implementations beyond the PostgreSQL source, here is a [list of known PostgreSQL drivers + SCRAM status](https://wiki.postgresql.org/wiki/List_of_drivers) ( I also have a [presentation](https://www.slideshare.net/jkatz05/get-your-insecure-postgresql-passwords-to-scram) on the topic that shows the workflow).

**Comment by lpil** [comment]
Hit into this today as SCRAM is used by https://fly.io/, a deployment platform that's pushing the BEAM quite hard at the moment.

**Comment by tsloughter** [comment]
Thanks @jkatz ! Wish I had not somehow missed this issue you raised 4 months ago and could have been on top of this for postgres 14!

**Comment by jkatz** [comment]
@tsloughter It's never too late to support SCRAM! 😉 I'd be happy to review your implementation.

**Comment by tsloughter** [comment]
@jkatz I've started on this but is it another case of postgres' "documentation" of the protocol only being the C code :) or is there some outline of the protocol somewhere?

**Comment by tsloughter** [comment]
Oh, I missed you have a presentation, maybe that'll be enough, I'll give it a look.

**Comment by jkatz** [comment]
It's implemented in accordance with the SCRAM RFC [5802](https://datatracker.ietf.org/doc/html/rfc5802) and because it uses SHA-256, RFC [7677](https://datatracker.ietf.org/doc/html/rfc7677).

The presentation you reference does cover some of the implementation specifics.

**Comment by tsloughter** [comment]
Update: I have it working (thanks to epgsql :) and just need to clean up the code a bit before opening a PR. Hopefully can get someone to review the code a bit (@lpil ?) so I don't just have to merge it.

**Comment by lpil** [comment]
I'm game

**Comment by tsloughter** [comment]
@lpil cool. I was able to do it over the weekend but can't figure out why there are broken tests completely unrelated to these changes :(. Realized I should just open the PR anyway so you can take a look, so will do that this morning.

**Comment by tsloughter** [comment]
Here it is: https://github.com/erleans/pgo/pull/58

I see I still need to move CI to github actions :(

**Comment by tsloughter** [comment]
Resolved by #58

**Comment by lpil** [comment]
Amazing! Thank you very much

**Comment by jkatz** [comment]
@tsloughter Thank you! I've updated the [PG wiki](https://wiki.postgresql.org/wiki/List_of_drivers#Open_Source) to indicate pgo supports SCRAM.
