### ISSUE TITLE
Is it possible to get more information when unable to connect to a database

### ISSUE THREAD

**Issue by lpil** [erleans/pgo#53]
Hello!

Thanks for this library, it rocks

I was wondering if there's a way to get more information out of PGO when it fails to connect due to incorrect credentials. Currently it seems to boot OK but once you attempt to make a query it returns `none_available`.

Postgrex will repeatly log that it has been unable to connect, which can be useful for telling there's an immediate problem when starting the application.

Thanks,
Louis

**Comment by tsloughter** [comment]
Ah, yup, definitely, should be simple enough to add.
