### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by lpil** [erleans/pgo#54]
Hello!

Can this library be used with IPv6? Looking at Elixir's Postgrex I believe I need to add `inet6` as a socket option but I could not spot a way to do this.

Thanks,
Louis

**Comment by tsloughter** [comment]
I don't recall. Should be simple to fix if not.

**Comment by lpil** [comment]
Fab, thanks. I've been looking at the source code and it looks fairly straightforward.

Do you have a preference for what the API should be?

```erl

-type pool_config() :: #{host => string(),
                         port => integer(),

                         %.... etc

                         %% TCP socket options
                         ipv => inet | inet6.
```

**Comment by lpil** [comment]
I had a crack at this by allowing the user to specify the `inet6` value to pass to `gen_tcp:connect` (as you can see here https://github.com/erleans/pgo/pull/55) but I was unable to get it to work.

I can't see any differences between this and how Postgrex works when given `socket_options: [:inet6]`, but in my test application on fly.io's ipv6 network I can connect with Postgres but not with PGO.

Can you see anything I've done wrong? I'm afraid I'm not very familiar with gen_tcp.

**Comment by tsloughter** [comment]
I don't see postgrex doing anything special for ipv6 and checked the fly.io docs and there is no mention of passing an option to ecto to setup ipv6, https://fly.io/docs/getting-started/elixir/#generate-the-app-and-deploy-with-postgres

**Comment by tsloughter** [comment]
Probably easiest if we just ping @ericmj :)

**Comment by lpil** [comment]
I've spoken to the folks at fly and they say you need to add `socket_options: [:inet6]` for it to work, which seems to be the case in my testing with Postgrex. Their documentation is a little patchy at the moment.

As far as I can tell adding the `socket_options: [:inet6]` option just adds the `inet6` option to `gen_tcp:connect` call, so I expected that to be sufficient for PGO, but it still failed in my test.

**Comment by tsloughter** [comment]
Hm, ok. I assume there is no useful error message or logs? I guess I'll just need to give this a try so I can play around with it.

**Comment by lpil** [comment]
Not that I can see, but I am a bit unwell so I may be messing something obvious up.

I'm starting the connections like so

```elixir
    {:ok, pid} =
      Postgrex.start_link(
        hostname: hostname,
        username: database,
        password: password,
        database: database,
        port: port,
        socket_options: [:inet6]
      )

    :pgo.start_pool(:default, %{
      host: String.to_charlist(hostname),
      port: port,
      user: String.to_charlist(database),
      password: String.to_charlist(password),
      database: String.to_charlist(database),
      pool_size: 5,
      ipv: :inet6
    })

    Process.register(pid, :postgrex_conn)
```

And using them like this

```elixir
    :pgo.query("select 1", [], %{pool: :default})
    |> IO.inspect(label: :pgo)

    Postgrex.query(:postgrex_conn, "select 1", [])
    |> IO.inspect(label: :postgrex)
```

Nothing is printed by starting the connections, and PGO returns `{:error, :none_available}` after a few seconds when making a query.

**Comment by michallepicki** [comment]
I just tried @lpil 's `ipv6` branch from #55 and it allowed me to connect to a local postgresql instance with `listen_addresses = '::1'` in `/etc/postgresql/13/main/postgresql.conf`, using this config:
```
[
 {pgo, [{pools, [{default, #{pool_size => 5,
                             host => "0::1",
                             database => "mydb",
                             user => "postgres",
                             password => "postgres",
                             ipv => inet6}}]}]}
].
```
(I cloned the repo, modified `config/example.config`, and successfully executed a query from `rebar3 shell`)

**Comment by lpil** [comment]
Ah fab, thanks. I've updated my PR to accept a list of socket options and I've asked a question on the Fly forums to see if there's something else they can think of that would prevent connections.

**Comment by lpil** [comment]
I added printing of this error here
https://github.com/erleans/pgo/blob/e356380d0ab71ae2139a4c84763a2ac02c1e40fa/src/pgo_connection.erl#L95

And I found this:
```erlang
{error,{unknown_message,authentication,<<0,0,0,10,83,67,82,65,77,45,83,72,65,45,50,53,54,0,0>>}}
```
Where the binary decodes to 
```
^@^@^@
SCRAM-SHA-256^@^@
```

So I think the problem is that PostgreSQL is using a newer authentication method that PGO does not yet support. I'll open a new issue.

**Comment by tsloughter** [comment]
Ah shit, do they require SCRAM. That has been on my list of things to do... I since postgrex supports it that it'll be easy to add since I can just copy the code :)

**Comment by lpil** [comment]
Support has been merged in, can close this after the next release

**Comment by tsloughter** [comment]
v0.12.0 was released
