### ISSUE TITLE
Insert json string into JSONB column

### ISSUE THREAD

**Issue by lpil** [erleans/pgo#71]
Hello!

I have a JSON string that I wish to insert into a JSONB column directly rather than parse into a map to then be serialized again by pgo. Is this possible?

Thanks,
Louis

**Comment by tsloughter** [comment]
That should work. The default is to just take whatever the user passes and assume it is json: https://github.com/tsloughter/pg_types/blob/master/src/pg_jsonb.erl#L21-L22

Only if you supply a `json_config` does it try to encode it, like `application:set_env(pg_types, json_config, {jsone, [], [{keys, atom}]}),`

**Comment by lpil** [comment]
Oh! I wonder what I did wrong. I'll have to try again and get back to you.

**Comment by tsloughter** [comment]
I noticed there is no test for this.. It only tests that encoding with jsone in pgo works, so I do need to add a test and maybe there is an issue :)

**Comment by tsloughter** [comment]
@lpil were you able to test this?

**Comment by lpil** [comment]
It works! I don't know what my error was. I'll have to dig in and re-open if I work out the issue.
