### ISSUE TITLE
tstzrange type

### ISSUE THREAD

**Issue by benbro** [erleans/pgo#8]
Are there plans to support [tstzrange](https://www.postgresql.org/docs/current/rangetypes.html) type?

**Comment by tsloughter** [comment]
Yes. I got them working on a branch but within a much larger changeset that won't be ready for a while. I may break it out to just that change and merge it in. It involves using https://github.com/tsloughter/pg_datatypes/ for all encode/decode, but the tstzrange specific functions could be taken and put into `pgo_protocol` for starters.

**Comment by benbro** [comment]
Sounds good. Anyway I can help?

**Comment by tsloughter** [comment]
Yea, if you want to add the tstzrange functions from pg_datatypes to `pgo_protocol` and send a PR I can accept that.

**Comment by tsloughter** [comment]
This branch https://github.com/erleans/pgo/tree/pg_types that uses https://github.com/tsloughter/pg_types is ready. I need to add a test for tstzrange but since tz is there the range support should work.

**Comment by benbro** [comment]
Thanks, I'll test it.

**Comment by benbro** [comment]
My 'sessions' table has a column 'period tstzrange'.
I'm using master which include pg_types and getting an error:
```erlang
pgo:query("SELECT period FROM sessions").
** exception error: no function clause matching pg_range:decode(<<6,0,0,0,8,0,2,46,1,1,67,213,40,0,0,0,8,0,2,46,1,1,201,
                                                                  245,24>>,
                                                                {type_info,3910,pg_range,[],default,<<"tstzrange">>,
                                                                           <<"range_send">>,<<"range_recv">>,-1,<<"range_out">>,
                                                                           <<"range_in">>,0,1184,[]}) 
     in function  pgo_protocol:decode_row0/5 (/project/_build/default/lib/pgo/src/pgo_protocol.erl, line 557)
     in call from pgo_handler:receive_loop0/6 (/project/_build/default/lib/pgo/src/pgo_handler.erl, line 384)
     in call from pgo_handler:extended_query/6 (/project/_build/default/lib/pgo/src/pgo_handler.erl, line 289)
     in call from pgo_handler:extended_query/5 (/project/_build/default/lib/pgo/src/pgo_handler.erl, line 73)
     in call from pgo:query/3 (/project/_build/default/lib/pgo/src/pgo.erl, line 102)
```

**Comment by tsloughter** [comment]
What is the value in the database? Forgot that right now range only supports the case that starts with `2` as the flag. One minute, I need to find the actual spec for postgres range encoding to get this right..

**Comment by benbro** [comment]
Several tests for inclusive, exclusive, infinity and -infinity:
```erlang
pgo:query("SELECT tstzrange('2019-06-22 08:00:00.000+00','2019-06-22 09:00:00.000+00', '[]');").
pgo:query("SELECT tstzrange('2019-06-22 08:00:00.000+00','2019-06-22 09:00:00.000+00', '[)');").
pgo:query("SELECT tstzrange('2019-06-22 08:00:00.000+00','infinity', '[]');").
pgo:query("SELECT tstzrange('-infinity','infinity', '[]');").
```
This is the code I'm using to decode tstzrange:
```erlang
-define(RANGE_EMPTY, 16#01). % range is empty
-define(RANGE_LB_INC, 16#02). % lower bound is inclusive
-define(RANGE_UB_INC, 16#04). % upper bound is inclusive
-define(RANGE_LB_INF, 16#08). % lower bound is -infinity
-define(RANGE_UB_INF, 16#10). % upper bound is +infinity
-define(RANGE_LB_NULL, 16#20). % lower bound is null
-define(RANGE_UB_NULL, 16#40). % upper bound is null
decode_tstzrange(<<Flags:8, B/binary>>) ->
    HasLBound = 0 =:= Flags band (?RANGE_EMPTY bor ?RANGE_LB_NULL bor ?RANGE_LB_INF),
    HasUBound = 0 =:= Flags band (?RANGE_EMPTY bor ?RANGE_UB_NULL bor ?RANGE_UB_INF),   
    case {HasLBound, HasUBound} of
        {true, true} ->
            <<L:32, LBound:L/binary, L:32, UBound:L/binary>> = B,
            {decode_timestamp(LBound), decode_timestamp(UBound)};
        {true, false} ->
            <<L:32, LBound:L/binary>> = B,
            {decode_timestamp(LBound), null};
        {false, true} ->
            <<L:32, UBound:L/binary>> = B,
            {null, decode_timestamp(UBound)};
        {false, false} -> {null, null}
    end.

decode_timestamp(<<16#7FFFFFFFFFFFFFFF:64/signed-integer>>) -> infinity;
decode_timestamp(<<-16#8000000000000000:64/signed-integer>>) -> '-infinity';
decode_timestamp(<<Timestamp:64/signed-integer>>) ->
    TimestampSecs = Timestamp div 1000000,
    USecs = Timestamp rem 1000000,
    decode_timestamp0(TimestampSecs, USecs).

-define(POSTGRESQL_GS_EPOCH, 63113904000).
decode_timestamp0(Secs, USecs) ->
    {Date, {Hour, Min, Secs0}} = calendar:gregorian_seconds_to_datetime(Secs + ?POSTGRESQL_GS_EPOCH),
    Secs1 = cast_datetime_usecs(Secs0, USecs),
    Time = {Hour, Min, Secs1},
    {Date, Time}.

cast_datetime_secs(Secs) ->    
    round(Secs).

cast_datetime_usecs(Secs0, USecs) ->
    Secs1 = case USecs of
        0 -> Secs0;
        _ -> Secs0 + USecs / 1000000
    end,
cast_datetime_secs(Secs1).
```

**Comment by tsloughter** [comment]
Thanks, was implementing that flag stuff in the generic pg_range module right now, this will help.

**Comment by tsloughter** [comment]
Please try again. I've added support for setting if it a bound is inclusive or not and `unbound`.

Open to suggests about how inclusivity is set. Right now it is a tuple `{{LowerInc, LowerBound}, {UpperInc, UpperBound}}`.

Could be a map or a differently structured tuple.

**Comment by benbro** [comment]
This is what I'm getting now. What does true means?
```erlang
pgo:query("SELECT tstzrange('2019-06-22 08:00:00.000+00','2019-06-22 09:00:00.000+00', '[]');").
#{command => select,num_rows => 1,
  rows =>
      [{{{true,{{2019,6,22},{8,0,0}}},
         {true,{{2019,6,22},{9,0,0}}}}}]}
```

**Comment by tsloughter** [comment]
If you mean the `true`s that is saying whether it is inclusive `[` or exclusive `(`.

**Comment by benbro** [comment]
{{LowerInc, LowerBound}, {UpperInc, UpperBound}} might be fine. It's a bit annoying to need to pattern match to get only LowerBound and UpperBound but not sure I have a better suggestion.

**Comment by benbro** [comment]
In SQL the syntax is:
```sql
SELECT tstzrange('2019-06-22 08:00:00.000+00','2019-06-22 09:00:00.000+00', '[]');
```
So maybe in erlang we could use:
{LowerBound, UpperBound, {LowerInc, UpperInc}}

Not sure what's better.

**Comment by benbro** [comment]
and if you are going with {LowerInc, LowerBound}, {UpperInc, UpperBound}} I would reverse the order to:
{LowerBound, LowerInc}, {UpperBound, UpperInc}}

**Comment by tsloughter** [comment]
Yea, I was considering ` {LowerBound, UpperBound, {LowerInc, UpperInc}}` as well because of the SQL syntax.

I'll think about a bit more but probably switch to that.

**Comment by tsloughter** [comment]
I've switched it to `{{LowerBound, UpperBound}, {LowerInc, UpperInc}}` and am closing this.
