### ISSUE TITLE
Docker compose failing in CI

### ISSUE THREAD

**Issue by chiroptical** [erleans/pgo#84]
https://github.com/erleans/pgo/blob/83e7859ba618a48ef0b5776148020837447ce5a7/.github/workflows/ct.yml#L24-L25

It is entirely possible this just needs to be `docker compose up -d`. Hopefully I can test this week.

**Comment by tsloughter** [comment]
Possibly. Could you send a PR?

**Comment by chiroptical** [comment]
Handled in #85
